codesydney/classified-ads-app-for-good

.github/workflows/ci.yml, client/.babelrc, client/jest-setup.js, client/jest.config.cjs, client/package.json, client/src/components/HelloWorld.jsx, client/src/components/HelloWorld.test.jsx, package-lock.json, package.json, server/jest.config.js, server/jsconfig.json, server/package.json, server/src/app.js, server/src/controllers/HealthController.js, server/src/routes/HealthRoute.js, server/src/services/HealthService.js, server/src/tests/controllers/HealthController.int.test.js, server/src/tests/services/HealthService.unit.test.js
The test configurations for both the client and server applications are now set up, along with basic unit tests for the client using React Testing Library and Jest. For the server, there are new unit and integration tests utilising Supertest and Jest. This includes tests for a newly created GET endpoint at **/api/v1/health**. These tests have been integrated into the CI process, automatically running with each commit to ensure ongoing code reliability.
https://github.com/codesydney/cs-directory/issues/12
Implemented tests for the /api/v1/health endpoint to verify its health status. Additionally, client-side unit tests have been developed to ensure functionality.
After each commit on your branch, notifications will indicate the status of the build, linting, and tests. Please make sure …
=> CSD-12 Test Config & CI

client/package.json, client/src/main.jsx, package-lock.json
- Installed Material UI and it's dependencies into the client-side project.
- NA
- https://github.com/codesydney/cs-directory/issues/2
- NA
- NA
- NA
=> CSD-2 Install Material UI

.gitignore, package-lock.json, server/package.json, server/src/config/db.js, server/src/index.js
This update introduces a config update to establish a connection with MongoDB. The config prioritises fetching MongoDB URI credentials from a `.env` file, facilitating two primary scenarios:
1. Connection to a database for integration testing purposes.
2. Connection to the main database.
(these credentials will soon be provided by @engramar 
As a secondary measure, should the `.env` file be unavailable (which would be the case initially) or not contain the necessary MongoDB credentials, the configuration gracefully defaults to using a local MongoDB instance. This fallback mechanism ensures that local testing and development can proceed without reliance on the `.env` file.
- https://github.com/codesydney/classified-ads-app-for-good/issues/16
To execute integration tests, use the command …
=> CA-16 Database Connection MongoDB

client/package.json, client/src/App.jsx, client/src/main.jsx, client/src/pages/About.jsx, client/src/pages/Contact.jsx, client/src/pages/Error.jsx, client/src/pages/Home.jsx, client/src/pages/Signin.jsx, client/src/pages/Signup.jsx, client/src/router/Router.jsx, package-lock.json
- This PR installs and configures react-router-dom for client side routing. 
- Adds Top level pages folder and corresponding components for routes: home, about, contact, signup, signin.
- Adds Hooks folder and utils folder (empty). 
- #19
=> Install and configure react router #19

package-lock.json, server/package.json, server/src/app.js, server/src/docs/api-docs.js, server/src/swaggerConfig.js
To enhance the developer experience and eliminate the ambiguity of encountering a 404 error page upon reaching the root URL, we have implemented an improvement. Now, when you access the root page at `http://localhost:3000`, you will be presented with the Swagger documentation interface. This change aims to provide immediate visibility into our API's endpoints and their respective functionalities.
Although this addition is not compulsory, we strongly recommend maintaining up-to-date documentation as new endpoints are introduced. This practice will facilitate a clearer understanding and ease of use for developers interacting with our server.
https://github.com/codesydney/classified-ads-app-for-good/issues/23
=> CA-23 Swagger Docs for Dev Env

.github/workflows/deploy.yml, client/vite.config.js
Modify name of server to classifieds.code.sydney
Can only be tested when pushed to main
=> Modify name of server to classifieds.code.sydney

.github/workflows/build-and-deploy.yml
Modify CI so that client and server artifacts are pushed to the server after successful testing.
This has been tested on a fork, but the real test has to be done after merging this into main.
=> Modify CI to push artifacts to prod server

package-lock.json, package.json, server/package.json, server/src/config/db.js, server/src/controllers/HealthController.js, server/src/controllers/UserController.js, server/src/index.js, server/src/routes/UserRoute.js, server/src/utils/catchAsync.js, server/src/utils/logger.js
Implemented the `catchAsync` utility function for streamlined error handling in controllers, enhanced logging with Pino for clarity and readability, and restructured middleware to integrate at the router level, enhancing overall code organisation and maintainability.
https://github.com/codesydney/classified-ads-app-for-good/issues/37
- Tests and pipeline should all still pass.
=> CA-37 Enhancements in Error Handling, Logging, and Middleware Organisation

server/src/utils/logger.js
Updated logger config for compatibility with CSC.
https://github.com/codesydney/classified-ads-app-for-good/issues/39
=> CA-39 CSC Compatible Logger Config

server/src/docs/api-docs.js
This PR enhances the Swagger documentation for the signin/signup modules by organising them into distinct sections, thereby improving readability and organisation.
https://github.com/codesydney/classified-ads-app-for-good/issues/43
=> CA-43 Swagger Docs Auth Endpoints

package-lock.json, server/package.json, server/src/migration/removeAutomatedUsers.js, server/src/migration/userMigration.js, server/src/models/User.js
This introduces a seed/migration script designed to automatically populate the database with 100 users, enhancing our ability to utilises the smart search functionality for user lookup. This script has been incorporated into the package.json file and is set to generate 100 users by default. However, the number of users can be adjusted by setting the NUM_USERS environment variable. Additionally, a new boolean attribute named isAutomated has been added to the User Schema, which defaults to false. When this script is executed, the `isAutomated` flag for each user is set to true. This addition lays the groundwork for a subsequent script intended for cleaning up users marked as automated from the database, ensuring our user data remains manageable and relevant …
=> CA-45 Users Data Seed/Migration

client/src/apis/UserAPI.js, client/src/apis/UserAPI.test.js, client/src/components/Users.jsx, client/src/pages/Home.jsx, server/src/controllers/UserController.js, server/src/docs/api-docs.js, server/src/models/User.js, server/src/services/UserService.js, server/src/tests/controllers/UserController.int.test.js
This PR introduces enhanced smart search functionality to the `/api/v1/users` endpoint, enabling partial search capabilities for `fullName`, `email`, and `serviceName`. Alongside the smart search feature, this update incorporates backend support for pagination and result limits to efficiently manage and navigate through the search results. Additionally, the Swagger documentation has been revised to accurately reflect these changes. While the primary focus of this PR is to bolster the backend capabilities, preliminary updates have been made to the frontend to utilise this enhanced search functionality. The frontend integration serves to demonstrate the API's new features in action. Enhancing the visual presentation and user experience of the search results on the frontend will be the …
=> CA-22 Enhanced Smart Search Functionality for Users Endpoint

client/package.json, client/postcss.config.js, client/src/components/RequestPasswordResetForm.jsx, client/src/components/ResetPasswordForm.jsx, client/src/components/SearchBar.jsx, client/src/components/SignInForm.jsx, client/src/components/SignUpForm.jsx, client/src/index.css, client/src/main.jsx, client/src/pages/RequestPasswordReset.jsx, client/src/pages/ResetPassword.jsx, client/src/pages/Signin.jsx, client/src/pages/Signup.jsx, client/tailwind.config.js, package-lock.json
Switch MUI to use Tailwind CSS
=> Tailwind CSS

server/src/services/UserService.js, server/src/tests/controllers/UserController.int.test.js
- Enhancement to the search to also perform partial string search
=> CA-51 Partial String Search Query Enhancement

client/src/App.jsx, client/src/components/Footer.jsx
Implemented a footer component
https://github.com/codesydney/classified-ads-app-for-good/issues/53
=> CA-53 Footer

client/src/pages/Signup.jsx
Fix link from the sign up page
=> CA-55 Fix Link

client/src/components/Footer.jsx, client/src/pages/Login.jsx, client/src/pages/RequestPasswordReset.jsx, client/src/pages/ResetPassword.jsx, client/src/pages/Signup.jsx
Fix the mobile view for Signup/Login module.
https://github.com/codesydney/classified-ads-app-for-good/issues/59
=> CA-59 Signup/Login Module Mobile View

client/src/components/RequestPasswordResetForm.jsx, client/src/pages/RequestPasswordReset.jsx, client/src/schema/index.js, server/src/utils/mail.js
Fixing the password reset request to be environment specific and enhance on the UI.
https://github.com/codesydney/classified-ads-app-for-good/issues/61
=> CA-61 Password Reset Request

client/src/components/SignUpForm.jsx, client/src/components/Users.jsx, client/src/schema/index.js, server/src/controllers/UserController.js, server/src/docs/api-docs.js, server/src/migration/userMigration.js, server/src/models/User.js, server/src/services/UserService.js, server/src/tests/controllers/UserController.int.test.js
- A short, clear and concise description of what this pull request do.
The Signup screen now includes the firstName and lastName fields
Swagger docs updated to accomodate this change
https://github.com/codesydney/classified-ads-app-for-good/issues/64
https://github.com/codesydney/classified-ads-app-for-good/issues/67
=> CA-64 Signup To Include FirstName and LastName

client/package.json, client/src/apis/UserAPI.js, client/src/components/LoginForm.jsx, client/src/components/RequestPasswordResetForm.jsx, client/src/components/ResetPasswordForm.jsx, client/src/components/SignUpForm.jsx, client/src/components/navbar/Navbar.jsx, client/src/components/navbar/UserMenu.jsx, client/src/features/auth/authAuction.js, client/src/features/auth/authSlice.js, client/src/features/authAuction.js, client/src/main.jsx, client/src/pages/Account.jsx, client/src/pages/Contact.jsx, client/src/router/ProtectedRoute.jsx, client/src/router/Router.jsx, client/src/store.js, package-lock.json, server/src/controllers/UserController.js, server/src/middleware/validationMiddlewares.js, server/src/routes/UserRoute.js, server/src/tests/controllers/UserController.int.test.js
Updated the navbar to be reflective of the user's authentication status.
https://github.com/codesydney/classified-ads-app-for-good/issues/66
=> CA-66 Dynamic Navbar Based on Auth Status

client/src/App.jsx, client/src/apis/UserAPI.js, client/src/components/LoginForm.jsx, client/src/components/SignUpForm.jsx, client/src/components/navbar/Navbar.jsx, client/src/components/navbar/UserMenu.jsx, client/src/features/auth/authAction.js, client/src/features/auth/authSlice.js, client/src/pages/Account.jsx, server/src/controllers/UserController.js, server/src/middleware/errorHandler.js, server/src/middleware/validationMiddlewares.js, server/src/middleware/verifyToken.js, server/src/models/PasswordResetToken.js, server/src/models/User.js, server/src/routes/UserRoute.js, server/src/services/PasswordResetService.js, server/src/services/UserService.js
Added a new endpoint to return the current logged in users for the Account Page.
https://github.com/codesydney/classified-ads-app-for-good/issues/70
=> CA-70 GET /me Endpoint FE & BE

server/src/models/User.js, server/src/services/UserService.js
Added full name virtuals and added more fields to DB index for string matching.
=> CA-65 FullName Virtuals & Search More Fields

client/src/App.jsx, client/src/apis/UserAPI.js, client/src/apis/UserAPI.test.js, client/src/components/navbar/UserMenu.jsx, client/src/features/auth/authAction.js, client/src/features/auth/authSlice.js, client/src/main.jsx, client/src/pages/MyProfile.jsx, client/src/providers/AuthProvider.jsx, client/src/router/Router.jsx, server/src/controllers/UserController.js, server/src/middleware/verifyToken.js, server/src/models/User.js, server/src/routes/UserRoute.js, server/src/services/UserService.js
Added a new endpoint and a basic UI on the My Profile Page to be able to update users profile. This is an API focused ticket only. The work to enhance the UI will be done as a separate ticket.
https://github.com/codesydney/classified-ads-app-for-good/issues/77
=> CA-77 PATCH profile/me Endpoint

client/src/apis/UserAPI.js, client/src/apis/UserAPI.test.js, client/src/components/search/User.jsx, client/src/features/auth/authAction.js, client/src/features/users/usersAction.js, client/src/features/users/usersSlice.js, client/src/pages/UserProfile.jsx, client/src/router/Router.jsx, server/src/controllers/UserController.js, server/src/middleware/authenticationStatus.js, server/src/routes/UserRoute.js, server/src/services/UserService.js
* **New endpoint for user profiles:** An endpoint has been introduced to retrieve user profiles.
* **Authentication middleware:** A new middleware layer verifies the presence and validity of tokens within request headers. This layer selectively determines which user data to return in the response.
* **Search function update:** The `searchUsers` function now incorporates the authentication middleware. Unauthenticated searches will receive limited responses excluding sensitive user information (PII). This approach aligns with how user profile data is handled.
**Viewing Users Profile (Unauthenticated)**
**Viewing Users Profile (Authenticated)**
https://github.com/codesydney/classified-ads-app-for-good/issues/79
=> CA-79 GET /api/profile/<userId> & authenticationStatus Middleware

server/src/controllers/UserController.js, server/src/middleware/authenticationStatus.js, server/src/migration/userMigration.js, server/src/models/User.js
**The User model now includes a new flag, `isOffer`. This flag indicates whether a user holds the position of USTAA Officer. It defaults to `false` as there are currently only a few designated officers, and programmatic assignment isn't implemented yet. Assigning the `isOffer` flag will be done manually through Atlas.**
**Benefits of being a USTAA Officer:**
* Access to view PII data of other users.
=> CA-82 isOfficer Flag & PII Restriction

client/src/apis/UserAPI.js, client/src/components/profile/settings/ChangePassword.jsx, client/src/components/profile/settings/ProfileSettings.jsx, client/src/features/auth/authAction.js, client/src/features/auth/authSlice.js, client/src/schema/index.js, server/src/controllers/UserController.js, server/src/routes/UserRoute.js
- client changes: create change password form
- Form working on client side, action created, api func created. 
-server changes: very basic endpoint created: PATCH /profile/password
- updatePassword controller func
NOTE TO PROMIE -> I'd like to have a crack at completing this endpoint if thats all good. 
https://github.com/codesydney/classified-ads-app-for-good/assets/62501585/4d305bdd-969d-4c07-9956-83d77aa46f2f
#7 
- [ x] Chrome
=> Alumni profile management

server/src/migration/userMigration.js, server/src/models/User.js, server/src/services/UserService.js
This update introduces the `isProfileComplete` flag within the user model, which serves as an indicator of whether a user's profile meets the criteria for being considered complete. To achieve this status, a user must provide all necessary information in the following fields:
```
- firstName
- lastName
- email
- suburb
- postcode
- story
- education.college
- education.course
- education.yearGraduated
```
Please note, the alumniProfilePicture field is currently omitted from this requirement but is scheduled for inclusion in a forthcoming update, which will integrate S3 image uploads. The criteria for a "complete" profile are pivotal, as only users meeting these conditions will be included in search results, enhancing the quality and relevance of search outputs for our platform users. …
=> CA-87 Implement isProfileComplete Flag and Filter Out Incomplete Profiles in Search

client/src/components/search/User.jsx, client/src/components/search/UserImg.jsx
Updated the UserImg component to display the `fullName` and `alumniProfilePicture` instead.
https://github.com/codesydney/classified-ads-app-for-good/issues/92
=> CA-92 Update UserImg Component

client/src/components/profile/ProfileNav.jsx, package-lock.json, server/package.json, server/src/controllers/UserController.js, server/src/routes/UserRoute.js, server/src/services/ImageUploadService.js, server/src/services/UserService.js
This update introduces a new backend API endpoint for alumni to upload their profile pictures. Please note that this is currently a back-end change only, and all demonstrations will be done through Postman for testing purposes. The client-side interface for uploading pictures will be addressed in a separate task. 
https://github.com/codesydney/classified-ads-app-for-good/issues/85
=> CA-85 Backend: PATCH users/profile/image

client/src/components/search/UserDetails.jsx, client/src/pages/UserProfile.jsx
- Added a user details component that will show alumnus/alumna information. Depending on whether a user is authorised, i.e., an officer, they will see the complete information, including personal details. If not, then only the public information will be displayed.
- https://github.com/codesydney/classified-ads-app-for-good/issues/98
- Public view (user), from the main page click view profile, then the user will land on the profile view page.
- Private view (officer), login then from the main page click view profile, then will land on the full profile view page.
- Could AQ please review the profile and check if there is any missing information? Also, could you confirm if non-officer users can access any personal information on the profile? 
- Additionally, can you verify if the link to …
=> Issue-98-detailed view of each alumnus/alumna

server/src/services/UserService.js
Added `story` to be displayed for public.
=> CA-105 include story to display as public

client/src/components/profile/InputGroup.jsx, client/src/components/profile/general/GeneralForm.jsx, client/src/components/search/User.jsx, client/src/components/search/UserDetails.jsx, client/src/schema/index.js, server/src/migration/userMigration.js
Added the State field in the General Tab under the Alumni Profile update.
https://github.com/codesydney/classified-ads-app-for-good/issues/108
=> CA-108 State Selection UI

client/src/components/navbar/UserMenu.jsx
- A short, clear and concise description of what this pull request do.
- Add screenshot where applicable.
- Add the link of the ticket this pull request is resolving.
- Where applicable, indicate the test results recorded.
- If manual tests are only applicable, outline the steps needed to perform the tests.
- Explain how your change should be reviewed, and where reviewers should direct their attention.
- Explain (where relevant) how your change can be tested.
=> Issue 110 Add Membership Payment Link

client/src/components/Avatar.jsx, client/src/components/navbar/UserMenu.jsx, client/src/components/search/SearchBar.jsx, client/src/features/auth/authSlice.js, client/src/pages/Home.jsx, client/src/router/ProtectedRoute.jsx, server/src/services/UserService.js
- Enhance search bar
- Include `isProfileComplete` in search results (bug fix)
- Improve `/users/me` endpoint if we get an error `localStorage.removeItem()` and set `isAuthenticated` to false to prevent spoofing of the accessToken.
=> Improvements

client/src/components/contact/ContactForm.jsx, client/src/components/search/UserDetails.jsx
- Fix Emailjs form error
- Prevent service button from displaying on public user profile when the service url field is null.
- [ x] Chrome
=> Small UI update and Emailjs form update.

client/src/components/Footer.jsx
=> CA-134 Fixed Typo

client/src/components/navbar/Logo.jsx, client/src/components/navbar/UserMenu.jsx
Fix the navigation bug fix that was reported.
=> CA-139 Navigation Bug Fix

server/src/models/User.js, server/src/services/UserService.js
Fields required to trigger the `isProfileComplete` to true are `firstName`, `lastName` and `email`. Essentially, by signing up, new registered users will have the `isProfileComplete` to true.
=> CA-147 isProfileComplete Required Fields Update

README.md, client/src/assets/developers/developers.json
Developer profile update - Promie
=> CA-99 Developer Profile Update - Promie
